"""add chapters column to learning_records

Revision ID: 758564245a5b
Revises: c967c95e7749
Create Date: 2026-05-25 20:59:28.003321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '758564245a5b'
down_revision: Union[str, None] = 'c967c95e7749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning_records', sa.Column('chapters', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning_records', 'chapters')
    # ### end Alembic commands ###
